#!/usr/bin/python
# -*- coding: utf-8 -*-

#图灵完备
#在可计算性理论里，如果一系列操作数据的规则（如指令集、编程语言、细胞自动机）可以用来模拟单带图灵机，那么它是图灵完备的。

#编程到底是什么
#编程是人与计算机的交互，人通过某种编程语言，也就是和计算机交互的某一种标准化的交流技巧（比如说有PHP，Python等），让计算机按照人的思维，输出特定的结果。

#for else
i=[1,2,3,4,5]
for r in i:
    print(r)
else:
    print("循环遍历已经完成")

#函数字符串文档，函数return
def noreturn():
'''this is a document, finsh print result(文档字符串)'''
    print("No Return")

def havereturm():
    a="Have Return"
    return a

print(noreturn())
print(havereturm())
#从结构来说，函数是为了实现特定输出的，如果没有return，会输出为 None，不完整
#文档字符串，用于写函数文档，让帮助文档更加清晰

#全局变量和局部变量
info1='info 1'
def info_father():
    info2='info 2'
    return info2

print(info_father())
#在一个py文件，info1是在这个py文件中的全局变量，info2是一个局部变量，因为处于函数内部

def func_global():
    '''关键字global表明，我要用全局变量y，不要用局部变量'''
    global y
    print 'y is', y
    #定义了局部变量，后面访问依然是这个局部变量，如果不再次定义x的话，依然会继续使用全局变量
    y = 50
    print 'Changed local y to', y

y = 10
func_global()
print 'Value of y is', y

#变量作用域
info='test'
def infotest():
    print(info)
#结果打印为test，是因为如果打印一个变量，python会先在函数内部搜寻，如果没有，再向外搜寻，info为全局变量，搜到了最后被打印出来

info=1111
def infotest():
    info=info+1
    print(info)
#结果打印为报错，当打印变量时，搜索变量info，info在这属于局部变量，找到了，但没有定义，报错
#python作用域，先在函数内部查找，再去嵌套函数查找，如果有嵌套的函数，再去全局查找，再去内置查找，再找不到，就报错了

#函数return只能返回一个值，但可以是任何类型
def infotest(a,b):
    return a,b
#返回为一个元组

#函数 可变参数
def infotest(a,b,*c):
    return a,b,c
print(infotest(1,2,3,4,5,6,9))
#返回值为(1, 2, (3, 4, 5, 6, 9)),实行一对一的方法，后面多余的都被打包成一个元组

def infotest(a,**b):
    return a,b
print (infotest(1,b=20,c=30))
#两颗星代表传递的是字典，输出结果为(1, {'c': 30, 'b': 20})

#import，当在一个函数内部导入，执行的便是局部导入，当在文件顶部导入的时候，就是应用到全局
def louistest(b,c):
    import math
    a=b+c
    return a

import math
def louistest():
    a=math.acos()
    return a

#只导入部分函数
from pandas import DataFrame
#相对导入和绝对导入依然有问题！！！！！！课上提问
#dir()返回值中有双下滑线的现在理解为内置方法，但有问题，需要进一步理解

#利用分支判断语句判断参数
def louistest(a,b,*c):
    if len(c)==1:
        if a==b:
            if a>c[0]:
                k='a,b相等，且都大于c,a和b的值为:'+str(a)
                return k
            elif a==c[0]:
                k='a,b,c都相等,值为:'+str(a)
                return k
            else:
                k='a,b相等,且都小于c,c值为:'+str(c[0])
        elif a>b:
            if a>c[0]:
                k='a最大,值为:'+str(a)
            elif a==c[0]:
                k='a,c相等，且最大,a和c的值为:'+str(a)
                return k
        else:
            if b>c[0]:
                k='b最大,值为:'+str(b)
                return k
    elif a==b:
        if a==max(c):
            k='a,b和列表c最大值相等,值都为'+str(a)
            return k
        elif a>max(c):
            k='a,b相等，且最大,a和b的值为:'+str(a)
            return k
        else:
            k='a,b相等，且列表c中值最大,列表c中的值为:'+str(c)
            return k
    elif a>b:
        if a>max(c):
            k='a为最大值,a的值为:'+str(a)
            return k
        elif a==max(c):
            k='a和列表c中最大值相等,a的值:'+str(a)
            return k
        else:
            k='列表c有最大值，且值为:'+str(max(c))
            return k

    else:
        if b==max(c):
            k='b和列表c最大值相等,b的值相等:'+str(b)
            return k
        elif b>max(c):
            k='b为最大值:'+str(b)
            return k
        else:
            k='列表c有最大值,最大值为:'+str(max(c))
            return k

print(louistest(19,12,89,8,232,90))

