#!/usr/bin/python
# -*- coding: utf-8 -*-

#module package
#一个 py 文件就是一个 module ，多个 module 组成一个 package

#if__name__='__main__'
#a.py

def louisa():
  a='louisa'
  return a

if __name__='__main__':
  louisa()
  
#b.py
def louisb():
  b='louisb'
  return b

if __name__='__main__':
    louisb()
    
#其中分别运行 a，b 文件的时候，if判断语句为真，是因为每个 module 都有一个属性，都为__main__,如果在一个 module 里面，打印此属性为 __main__，所以可以


